#!/bin/bash
# Builds the app and the Safari extensions with swiftc alone and produces build/SafariAdBlock.app.
# Needs only the Command Line Tools, not Xcode. (rules/*.json is generated by ./update-rules.sh)
# Signing: CODESIGN_IDENTITY env var → Apple Development → Developer ID → ad hoc, in that order.
set -euo pipefail
cd "$(dirname "$0")"
export LC_ALL=en_US.UTF-8

APP_NAME=SafariAdBlock
BUNDLE_ID=com.jhunos.SafariAdBlock
MIN_OS=13.0
ARCHS="${ARCHS:-arm64 x86_64}"
EXTENSIONS="Ads Privacy Korea"      # content blockers
WEB_EXT=VideoAdSkip                 # Safari web extension (video ad skipper)
BUILD_NUMBER=$(date +%Y%m%d%H%M)
SDK=$(xcrun --show-sdk-path)
OUT=build
APP="$OUT/$APP_NAME.app"
OBJ="$OUT/obj"

display_name() {
  case "$1" in
    Ads) echo "Ad Blocking" ;;
    Privacy) echo "Tracker Blocking" ;;
    Korea) echo "Korean Sites Ad Blocking" ;;
    VideoAdSkip) echo "Video Ad Skipper" ;;
    *) echo "$1" ;;
  esac
}

for ext in $EXTENSIONS; do
  if [ ! -f "rules/$ext.json" ]; then
    echo "rules/$ext.json is missing; downloading and converting the filter lists (network required)…"
    ./update-rules.sh
    break
  fi
done

rm -rf "$APP" "$OBJ"
mkdir -p "$OBJ" "$APP/Contents/MacOS" "$APP/Contents/Resources" "$APP/Contents/PlugIns"

# compile <output file> <module name> <swiftc arguments and sources…> — builds each architecture and merges them into a universal binary
compile() {
  local out=$1 module=$2; shift 2
  local slices=()
  for arch in $ARCHS; do
    swiftc -O -parse-as-library -module-name "$module" -sdk "$SDK" -target "$arch-apple-macos$MIN_OS" \
      "$@" -o "$OBJ/$module-$arch"
    slices+=("$OBJ/$module-$arch")
  done
  lipo -create "${slices[@]}" -output "$out"
}

echo "Building app ($ARCHS)…"
compile "$APP/Contents/MacOS/$APP_NAME" "$APP_NAME" \
  -framework SwiftUI -framework AppKit -framework SafariServices Sources/App/*.swift
sed "s/__BUILD__/$BUILD_NUMBER/g" Resources/App/Info.plist > "$APP/Contents/Info.plist"
printf 'APPL????' > "$APP/Contents/PkgInfo"

if [ ! -f Resources/App/AppIcon.icns ]; then
  echo "Generating app icon…"
  rm -rf "$OBJ/AppIcon.iconset"
  swift tools/make-icon.swift "$OBJ/AppIcon.iconset"
  iconutil -c icns "$OBJ/AppIcon.iconset" -o Resources/App/AppIcon.icns
fi
cp Resources/App/AppIcon.icns "$APP/Contents/Resources/AppIcon.icns"

for ext in $EXTENSIONS; do
  echo "Building extension: $ext ($(display_name "$ext"))…"
  APPEX="$APP/Contents/PlugIns/$ext.appex"
  mkdir -p "$APPEX/Contents/MacOS" "$APPEX/Contents/Resources"
  compile "$APPEX/Contents/MacOS/$ext" "$ext" \
    -application-extension -framework Foundation -framework AppKit \
    -Xlinker -e -Xlinker _NSExtensionMain -Xlinker -application_extension \
    Sources/ContentBlocker/*.swift
  sed -e "s/__NAME__/$ext/g" -e "s/__BUNDLE_ID__/$BUNDLE_ID/g" \
      -e "s/__DISPLAY__/$(display_name "$ext")/g" -e "s/__BUILD__/$BUILD_NUMBER/g" \
      -e "s/__POINT__/com.apple.Safari.content-blocker/g" -e "s/__PRINCIPAL__/ContentBlockerRequestHandler/g" \
      Resources/Extension/Info.plist > "$APPEX/Contents/Info.plist"
  cp "rules/$ext.json" "$APPEX/Contents/Resources/blockerList.json"
  cp "rules/$ext.meta.json" "$APPEX/Contents/Resources/meta.json"
done

echo "Building extension: $WEB_EXT ($(display_name "$WEB_EXT"))…"
APPEX="$APP/Contents/PlugIns/$WEB_EXT.appex"
mkdir -p "$APPEX/Contents/MacOS" "$APPEX/Contents/Resources/images"
compile "$APPEX/Contents/MacOS/$WEB_EXT" "$WEB_EXT" \
  -application-extension -framework Foundation -framework AppKit -framework SafariServices \
  -Xlinker -e -Xlinker _NSExtensionMain -Xlinker -application_extension \
  Sources/WebExtension/*.swift
sed -e "s/__NAME__/$WEB_EXT/g" -e "s/__BUNDLE_ID__/$BUNDLE_ID/g" \
    -e "s/__DISPLAY__/$(display_name "$WEB_EXT")/g" -e "s/__BUILD__/$BUILD_NUMBER/g" \
    -e "s/__POINT__/com.apple.Safari.web-extension/g" -e "s/__PRINCIPAL__/SafariWebExtensionHandler/g" \
    Resources/Extension/Info.plist > "$APPEX/Contents/Info.plist"
cp WebExtension/manifest.json WebExtension/background.js WebExtension/main.js WebExtension/content.js WebExtension/content.css "$APPEX/Contents/Resources/"
for px in 64 128; do
  sips -s format png -z $px $px Resources/App/AppIcon.icns --out "$APPEX/Contents/Resources/images/icon-$px.png" >/dev/null
done

# Signing — extensions first, then the app (the app signature seals PlugIns)
IDENTITY="${CODESIGN_IDENTITY:-}"
if [ -z "$IDENTITY" ]; then
  IDS=$(security find-identity -v -p codesigning 2>/dev/null || true)
  for PATTERN in "Apple Development" "Developer ID Application" "Apple Distribution"; do
    IDENTITY=$(echo "$IDS" | grep -F "$PATTERN" | head -1 | sed -E 's/.*"(.*)".*/\1/' || true)
    [ -n "$IDENTITY" ] && break
  done
fi
if [ -n "$IDENTITY" ]; then
  echo "Signing with: $IDENTITY"
  echo "$IDENTITY" > "$APP/Contents/Resources/signing.txt"
  SIGN=(codesign --force --sign "$IDENTITY")
else
  echo "Signing: ad hoc (no certificate found) — Safari will need 'Allow unsigned extensions'. See README."
  echo "adhoc" > "$APP/Contents/Resources/signing.txt"
  SIGN=(codesign --force --sign -)
fi
for ext in $EXTENSIONS $WEB_EXT; do
  "${SIGN[@]}" --entitlements Resources/Extension/Extension.entitlements "$APP/Contents/PlugIns/$ext.appex"
done
"${SIGN[@]}" --entitlements Resources/App/App.entitlements "$APP"
codesign --verify --deep --strict "$APP"
rm -rf "$OBJ"
echo "Done: $APP"
